Initial Commit of ABSIS Pro-Micro
jrsteensen/OpenHornet pull request #1118
Opened 2024-10-20 15:16 UTC by kbastronomics

Contains the Open Hornet Version of the Pro-Micro 1.3 PCB. 5 were ordered from JLCPCB and validated as working as expected.

# Description

This is the initial pull request for the ABSIS Pro-Micro PCB.

Addresses # 1114

## Motivation and Context
The available Pro-Micro's have a random issue on some board where the RAW power if used will cause the on-board regulator and associated capacitor to blow.   This resolves that issue

## Type of change
New PCB Design

Please delete options that are not relevant.

- [X] ECAD - New PCB (A new PCB!)

# How Has This Been Tested?

Multiple Iterations of the PCB ordered and tested thru JLCPCB
Burned Bootloader, Flashed with OH Code and validated,   
Applied up to 15v on RAW pin with no signed of failure.

# Screenshots:
did not exist prior
![ABSIS_Pro_Micro_TOP_ISO](https://github.com/user-attachments/assets/91d9f78e-ad58-4942-9fb1-32ff6f567876)
![ABSIS_Pro_Micro_BOT](https://github.com/user-attachments/assets/11b0bf53-62b6-47e0-93fc-62860b5becee)
![ABSIS_Pro_Micro_BOT_ISO](https://github.com/user-attachments/assets/218554c6-985e-4e2c-8013-a5a415e0a969)
![ABSIS_Pro_Micro_TOP](https://github.com/user-attachments/assets/62655e90-5012-40d5-a9f2-34fc05eed67c)

# Checklist: (Delete non-relevant sections)

## PCB/ECAD:
- [X] Requirements definition completed as a note on the schematic?
- [X] Schematic completed?
- [X] PCB laid out?
- [X] PCB routed?
- [X] PCB constrained by physical footprint limitations?
- [X] PCB critical component location requirements met?
- [X] Version number updated on PCB silkscreen, and the PCB and schematic docs?
- [X] Schematic/PCB reviewed?
- [X] BOM generated?
- [X] Gerbers generated?
- [X] MCAD generated?
- [ ] Has the fabrication files and a PDF of the schematic been copied to the ECAD folder of the release folder?

2024-10-20 15:51 UTC, jrsteensen requested changes
- [ ] Add markdown file with flashing firmware in the JLCPCB production files folder.
- [ ] Copy JLCPCB production files folder and PDF of schematic to release folder.

2024-10-20 15:51 UTC, jrsteensen commented on ECAD/PCBs/ABSIS/ABSIS Pro Micro/ABSIS_Pro_Micro.kicad_sch
- [ ] Use OH title block: (Can add note next to it to do the Sparkfun attribution.)
![image](https://github.com/user-attachments/assets/83bcd37f-5f45-47cb-b5b2-6212e79f8af6)
![image](https://github.com/user-attachments/assets/493f3ace-1650-408a-b473-9e9a3aeee6f7)

- [ ] Missing datasheet fields for shown components.
![image](https://github.com/user-attachments/assets/ec0d49f8-6c6c-4d69-8451-8b0b2fe5c6a9)

- [ ] Rev should be 1.4.0 (to align with on-attrition basis of updating how we rev PCBs.)

2024-10-20 15:51 UTC, jrsteensen commented on ECAD/PCBs/ABSIS/ABSIS Pro Micro/ABSIS_Pro_Micro.kicad_pcb
- [ ] Use OH Title Block
![image](https://github.com/user-attachments/assets/41e64834-8912-458d-af04-8a6ab174c98e)

- [ ] Link Rev to Rev Silkscreen so it updates when the page settings are updated automatically.
![image](https://github.com/user-attachments/assets/5cafe8a7-ec81-4fad-9b29-a8ca1a1c754c)

- [ ] Info should be in title block
![image](https://github.com/user-attachments/assets/e127ca93-45ad-410b-8d9c-bd1f065e75fd)

2024-10-20 19:47 UTC, jrsteensen commented
![image](https://github.com/user-attachments/assets/c4949e4a-8a46-4e6b-87af-f2afe9a11ef3)

Also, are there basic (for the cap) or high stock number parts that can be substituted in the design for these parts?

2024-10-26 03:27 UTC, kbastronomics commented
Title block updated on Schematic and PCB
attributions moved
update 22pf cap
Green LED was out of stock at time you looked
Added a note for a possible alternative for the USB connector (untested)
working on markdown for firmware instructions
will submit PR again when firmware instructions are ready

2025-03-31 05:51 UTC, closed without merging