MS21384-04 DNN Knob Update & Replacement of Obsolete Rotary Switch
jrsteensen/OpenHornet pull request #297
Opened 2021-01-30 12:37 UTC by L-Walker

# Description
## Change 1
Re-made the indication line on the knob, both black and white lines have been made in line with the MS Spec. The black line is inlaid .2mm deep, the white a further .2mm deep allowing .2mm layer height prints to differentiate the difference and creates a trench for the paint to easily fill. The Appearance color has been changed to the correct RGB conversion of FS595C Color 36231. NOTE: This color looks very dark when working in the assembly but is correct as can be seen in the render below.

![SNSR Panel Front](https://user-images.githubusercontent.com/65761897/106356319-e37cb100-6352-11eb-958d-0494d206e4cc.JPG)

![MS21384-04DNN](https://user-images.githubusercontent.com/65761897/106356265-83860a80-6352-11eb-9148-2c830a2540d8.JPG)
## Change 2
The HS-13Z rotary on the SNSR panel has been replaced with the A12505RNZQ as per issue #243 

![SNSR Panel Back](https://user-images.githubusercontent.com/65761897/106356393-5dad3580-6353-11eb-9f6e-f08f5ac2c92b.JPG)

## Type of change

- [ ] New MCAD (new Mechanical Model)
- [ ] Change MCAD (fixed issue with existing MCAD model)
- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
 
Test A Solidworks Collision Check - Results negative.
Test B Visual inspection - No collisions were found.

Test Configuration:

Hardware: Windows 10 Pro Version: 20H2
Toolchain: Solidworks Premium 2019 SP4.0
SDK:

# Checklist:

## MCAD:
- [ ] Model is in SolidWorks 2019 format
- [ ] Design intent and requirements have been met
- [ ] Design has been fit checked to ensure no interferences exist
- [ ] Design has been integrated into Next Higher Assembly (NHA)

2021-01-30 22:19 UTC, jrsteensen approved these changes

2021-01-30 22:45 UTC, jrsteensen requested changes
@L-Walker Can you review the commits in this branch and make sure all files listed are impacted by this change? I'm seeing several conflicts, and need your input.

2021-01-31 01:47 UTC, L-Walker commented
Delete the assemblies in question and merge.

2021-02-02 04:39 UTC, L-Walker commented
Going to Sinbin this PR, have made the changes incrementally with commits to ABSIS 2.0

2021-02-02 04:39 UTC, closed without merging